name: "CI/CD for Nginx Web App using GHA"

on:
  push:
    branches: ["main"]
    #paths-ignore:
    # - "src/*"
  pull_request:
    branches: ["main"] 

permissions:
  contents: read  

jobs:
  nginx-image-build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GITUSER_TOKEN }}

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata for the Docker Image #https://github.com/docker/metadata-action#tags-input
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build Image and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./Nginx-Deployment
          file: ./Nginx-Deployment/Dockerfile
          push: true
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
        
